# Generated by Django 5.0.6 on 2024-07-09 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("EMAIL", "EMAIL"),
                            ("PUSH", "PUSH"),
                            ("WHATSAPP", "WHATSAPP"),
                        ],
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_id",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("CANCELLED", "CANCELLED"),
                            ("SENT", "SENT"),
                            ("ERROR", "ERROR"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        max_length=9,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("local_date_time", models.DateTimeField()),
                ("destination", models.CharField(max_length=255)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entity.channel"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entity.status"
                    ),
                ),
            ],
        ),
    ]
