# Generated by Django 5.0.6 on 2024-07-12 14:42

from django.db import migrations

from ..enums import ChannelsEnums, StatusEnums


def create_initial_data(apps, schema_editor):
    Channel = apps.get_model("entity", "Channel")
    Status = apps.get_model("entity", "Status")

    Channel.objects.bulk_create(
        [Channel(channel_id=tag.value) for tag in ChannelsEnums]
    )
    Status.objects.bulk_create([Status(status_id=tag.value) for tag in StatusEnums])


class Migration(migrations.Migration):

    dependencies = [
        ("entity", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_initial_data)]
